version: 2

updates:
  - package-ecosystem: "bundler"
    directory: "/"
    target-branch: upgrade-deps-for-security
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/"
    target-branch: upgrade-deps-for-security
    schedule:
      interval: "daily"